app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.8
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host home.fullstackjam.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: homepage-tls-certificate
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
          providers:
            longhorn:
              url: http://192.168.2.161
        widgets.yaml: |
          - longhorn:
              # Show the expanded view
              expanded: true
              # Shows a node representing the aggregate values
              total: true
              # Shows the node names as labels
              labels: true
              # Show the nodes
              nodes: true
              # An explicit list of nodes to show. All are shown by default if "nodes" is true
              include:
                - homelab-5
                - homelab-6
                - homelab-0
        services.yaml: |
          - Development:
            - Gitea:
                href: https://git.fullstackjam.dev
                description: Git forge
                icon: gitea.svg
            - ArgoCD:
                href: https://argocd.fullstackjam.dev
                description: Continuous deployment
                icon: argocd.svg
            - Registry:
                href: https://harbor.fullstackjam.dev
                description: Container registry
                icon: docker.svg
            - Grafana:
                href: https://grafana.fullstackjam.dev
                description: Observability dashboards
                icon: grafana.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.fullstackjam.dev
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.fullstackjam.dev
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Documentation:
              - href: https://homelab.fullstackjam.dev
                icon: google-docs.svg
            - Public homelab repository:
              - href: https://github.com/fullstackjam/homelab
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Terraform Cloud:
              - href: https://app.terraform.io
                icon: terraform.svg
          - Infrastructure:
            - Router:
              - href: https://openwrt
                icon: router.svg
            - Proxmox:
              - href: https://proxmox:8006
                icon: proxmox.svg
            - Aliyun:
              - href: https://home.console.aliyun.com/
                icon: google-cloud-platform.svg
