app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/excalidraw/excalidraw
            tag: latest
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host draw.fullstackjam.dev
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: excalidraw-tls-certificate
