cilium_kube_proxy_replacement: strict
cilium_l2announcements:
  - cidr: 192.168.2.180/29

cilium_enable_hubble: true
cilium_enable_hubble_metrics: true
cilium_hubble_metrics:
  - dns
  - drop
  - tcp
  - flow
  - icmp
  - http
cilium_hubble_install: true
cilium_hubble_tls_generate: true
