cilium_kube_proxy_replacement: strict

cilium_enable_hubble: true
cilium_enable_hubble_metrics: true
cilium_hubble_metrics:
  - dns
  - drop
  - tcp
  - flow
  - icmp
  - http
cilium_hubble_install: true
cilium_hubble_tls_generate: true
