- name: Install necessary packages for Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == "Debian"
  loop:
    - curl
    - wget
    - git
    - zsh
    - lm-sensors
    - net-tools
    - traceroute
    - make
    - build-essential
    - apt-transport-https
    - ca-certificates
    - gnupg

- name: Install necessary packages for Fedora
  dnf:
    name: "{{ item }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  loop:
    - curl
    - wget
    - net-tools
    - traceroute
    - git
    - make
    - lm-sensors
    - zsh

- name: Install Development Tools group for Fedora
  shell: sudo dnf groupinstall -y "Development Tools"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh
  environment:
    PROFILE: "{{ ansible_env.HOME }}/.profile"

- name: Install oh-my-zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: ~/.oh-my-zsh
  environment:
    ZSH: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install oh-my-zsh plugins
  shell: |
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Configure .zshrc with desired plugins
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins='
    line: 'plugins=(git kubectl helm zsh-autosuggestions zsh-syntax-highlighting)'
    create: yes

- name: Change default shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh

- name: Install Node.js using nvm
  shell: >
    source ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts
  args:
    executable: /bin/bash
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"

- name: Add Helm repository for Ubuntu and Fedora
  shell: |
    curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
    sudo apt-get install apt-transport-https --yes
    echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt-get update
  when: ansible_facts['os_family'] == "Debian"

- name: Install Helm for Ubuntu
  apt:
    name: helm
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Helm for Fedora
  shell: |
    sudo dnf install https://get.helm.sh/helm-v3.10.3-linux-amd64.tar.gz
  when: ansible_facts['os_family'] == "RedHat"
