grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.fullstackjam.dev
    tls:
      - secretName: grafana-general-tls
        hosts:
          - *host
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: monitoring-system
    datasources:
      enabled: true
      searchNamespace: monitoring-system
  grafana.ini:
    server:
      root_url: https://grafana.fullstackjam.dev
  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
    size: 2Gi
