- name: Install iSCSI tools on Debian/Ubuntu
  apt:
    name: open-iscsi
    state: present
  when: ansible_os_family == "Debian"

- name: Install iSCSI tools on RedHat/CentOS/Fedora
  yum:
    name: iscsi-initiator-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure iSCSI service is enabled and started (Debian/Ubuntu)
  service:
    name: open-iscsi
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"

- name: Ensure iSCSI service is enabled and started (RedHat/CentOS/Fedora)
  service:
    name: iscsid
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat"
