kube-prometheus-stack:
  grafana:
    enabled: true
    forceDeployDatasources: true
    forceDeployDashboards: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - &host grafana.fullstackjam.dev
      tls:
        - secretName: grafana-general-tls
          hosts:
            - *host
    persistence:
      enabled: true
      type: sts
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  alertmanager:
    alertmanagerSpec:
      containers:
        - name: ntfy-relay
          image: ghcr.io/khuedoan/webhook-transformer:v0.0.3
          args:
            - --port=8081
            - --config=/config/alertmanager-to-ntfy.jsonnet
            - --upstream-host=https://ntfy.sh
          envFrom:
            - secretRef:
                name: webhook-transformer
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: webhook-transformer
    config:
      route:
        receiver: ntfy
        group_by:
          - namespace
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        routes:
          - receiver: ntfy
            matchers:
              - alertname = "Watchdog"
      receivers:
        - name: ntfy
          webhook_configs:
            - url: http://localhost:8081
              send_resolved: true
